### ISSUE TITLE
unable to import produceOn

### ISSUE THREAD

**Issue by initplatform** [nilsmehlhorn/ngrx-wieder#22]
If I look in the bundle it doesn't look like it is exported anywhere. 

<img width="678" alt="Screen Shot 2020-12-10 at 11 17 50 AM" src="https://user-images.githubusercontent.com/47506789/101798746-7464a800-3ad9-11eb-8462-9b5064327575.png">

```
        "ngrx-wieder": "4.0.0",
```

**Comment by initplatform** [comment]
Cool. BTW great project 👍

**Comment by nilsmehlhorn** [comment]
Fix released in `4.0.1`

**Comment by nilsmehlhorn** [comment]
The example now also uses `produceOn`:
https://github.com/nilsmehlhorn/ngrx-wieder-example/blob/df086f81a23222040db69b5e64f34e07e64baac7/src/app/on.reducer.ts#L40
