### ISSUE TITLE
angular 13 support

### ISSUE THREAD

**Issue by tlinford** [nilsmehlhorn/ngrx-wieder#54]
Hey @nilsmehlhorn, was looking with interest at this library and am wondering whether you still plan to keep it up to date?

I did some testing locally and was able to get it working with angular 13, I can tidy things up and open a pr if you want, but was basically wondering first of all if the project is still alive.

Thanks :)

**Comment by nilsmehlhorn** [comment]
Hey @tlinford, thanks for reaching out, updating the library now :slightly_smiling_face:

**Comment by nilsmehlhorn** [comment]
Closed by #56 and released in [v8.0.0](https://github.com/nilsmehlhorn/ngrx-wieder/releases/tag/v8.0.0)
