### ISSUE TITLE
is there a version of this lib for Angular 14

### ISSUE THREAD

**Issue by born2net** [nilsmehlhorn/ngrx-wieder#67]
is there a version of this lib for Angular 14
thanks for a great lib,

Sean

**Comment by born2net** [comment]
is the project still maintained? thank you.

**Comment by wen9218** [comment]
Hi, @nilsmehlhorn 
I need also the updated lib for ng v14.

Thanks

**Comment by alonms** [comment]
I also really need support for NG 14, please help

**Comment by nilsmehlhorn** [comment]
I'll update this weekend.

**Comment by seangithub11** [comment]
thank you very much. would really appreciate it fix as well. Will it look forward to having it this weekend as we are trying to upgrade and need to use the force flag due to the library. thanks 🙏

**Comment by nilsmehlhorn** [comment]
Released in v9.0.0

**Comment by wen9218** [comment]
Thank you, @nilsmehlhorn

**Comment by seangithub11** [comment]
thanks for fix

**Comment by born2net** [comment]
tx <3
