### ISSUE TITLE
support for angular v16,  @ngrx/store v16

### ISSUE THREAD

**Issue by ChristianFenkart** [nilsmehlhorn/ngrx-wieder#83]
Package "ngrx-wieder" has an incompatible peer dependency to "@ngrx/store" (requires "^15.0.0", would install "16.0.0").

**Comment by wen9218** [comment]
Hi,
@nilsmehlhorn , yeah, I have same issue of @ChristianFenkart 
Thanks for checking issue.

**Comment by born2net** [comment]
Hi and thank you got a great project.
we also can't use the wieder with Angular 16, any ETA? thank you!
Sean

**Comment by nilsmehlhorn** [comment]
Looking into it this weekend.

**Comment by born2net** [comment]
tx so much... looking fwd to it!

**Comment by born2net** [comment]
thanks so much for the help, great lib <3
