### ISSUE TITLE
Ngrx V17 Support

### ISSUE THREAD

**Issue by ChristianFenkart** [nilsmehlhorn/ngrx-wieder#87]

**Comment by born2net** [comment]
yes. please add support for v17. Thank you for a great lib!

**Comment by faileon** [comment]
Would also love to see this. Should be simple upgrade from 16 to 17.

**Comment by nilsmehlhorn** [comment]
I'll find time tomorrow to update, sorry for the delay.

**Comment by nilsmehlhorn** [comment]
The update is done, however, the release to npm may still take 1-3 days, again, sorry for the delay. I'll comment again, once it's released.

**Comment by born2net** [comment]
THANK YOU <3

**Comment by nilsmehlhorn** [comment]
v12 is now on npm 🙂
