### ISSUE TITLE
Please add support for Angular v18

### ISSUE THREAD

**Issue by wen9218** [nilsmehlhorn/ngrx-wieder#90]
Hi, @nilsmehlhorn , could you release new version for supporting Angular18?

Thank you

**Comment by born2net** [comment]
yes please, need to move to ngv18 and waiting on this lib <3 TX!

**Comment by born2net** [comment]
hello, any news on this? Thank you for a great lib!

**Comment by born2net** [comment]
Hello,
any chance we can get this fixed to ng 18 as it's the last lib we are waiting on so we can transition to v18.
thanks you for all the help.

**Comment by nilsmehlhorn** [comment]
Currently unavailable, best I can do is upgrade in 3 weeks

**Comment by born2net** [comment]
3 weeks would be awesome, greatly appreciated and thank you for a great lib <3

**Comment by nilsmehlhorn** [comment]
Support for Angular 18 now provided via v13

**Comment by born2net** [comment]
thank you SO much!
